[storage]
provider = "alist"

[storage.local]
upload_path = "uploads/avatars"
base_url = "/static/avatars"

[storage.alist]
version = 3
url = "your-alist-instance.com"
upload_path = "_imageStore"
token = "123456"
username = ""
password = ""
access_path = ""
access_domain = ""
filename_template = ""
